### ISSUE TITLE
"BACKSTAB.2DA", "SNEAKATT.2DA", "CRIPPSTR.2DA" should be tweaked

### ISSUE THREAD

**Issue by 4Luke4** [Argent77/A7-add_kit_ex#1]
At least on v2.5+, these files work for all classes and kits. The only issue is that the Record Screen won't display any information about these modifiers in this case.

As a result, you might want to replace the following clause _"This argument should only be provided for thief and ranger kits and will be ignored for other classes."_ with another one about the Record Screen...

**Comment by 4Luke4** [comment]
Calling also @FredrikLindgren.

**Comment by Argent77** [comment]
Interesting. It looks like all thieving-related tables can be used for any class/kit combination in EE games (including traplimt.2da).

**Comment by 4Luke4** [comment]
> Interesting. It looks like all thieving-related tables can be used for any class/kit combination in EE games (including traplimt.2da).

Even more interesting. Anyway, I think only these three (and "TRAPLIMT.2DA"...?) are somewhat meaningful for the other classes/kits...

**Comment by Argent77** [comment]
Theoretically it is even possible to expand "thiefskl", so that fighters or clerics can assign skill points at level up (provided there are thieving skills unlocked via "thiefscl").

**Comment by 4Luke4** [comment]
> Theoretically it is even possible to expand "thiefskl", so that fighters or clerics can assign skill points at level up (provided there are thieving skills unlocked via "thiefscl").

What do you mean exactly? I mean, Fighters or Clerics do not have the Pick Lock/Hide in Shadows buttons... Or are you saying that it's possible to list other skills (not related to Thieving, e.g.: Turn Undead)?

**Comment by 4Luke4** [comment]
> Or are you saying that it's possible to list other skills (not related to Thieving, e.g.: Turn Undead)?

It seems that all values from "STATS.IDS" are valid...? Again, the (big..?) problem is the UI: it must be updated accordingly or you'll get stuck during Character Creation/Level Up screen (when you're asked to spend your points among the available options...). If the UI can't be updated, then I guess it's pretty useless...

**Comment by Argent77** [comment]
"thiefskl" seems to affect only skills listed in "thiefscl".

Only few thieving skills can be (theoretically) used by non-thieves though, such as setting traps and maybe detect illusion. Everything else requires special toolbar buttons which are not available by default for these classes.

**Comment by 4Luke4** [comment]
> "thiefskl" seems to affect only skills listed by "thiefscl".

Yes–ish. I tried adding RESISTELECTRICITY to "THIEFSCL.2DA" and FIGHTER to "THIEFSKL.2DA". As expected, I was asked to spend my START_POINTS among the available skills (only RESISTELECTRICITY in this case) during Character Creation. The problem is that the UI **does not** support that skill, so you're basically stuck there (so, theoretically, all values from STATS.IDS are valid...). Unfortunately, I don't think the UI can be updated to support all values from STATS.IDS...

On the other hand, if you enable FIGHTERs to spend points among the usual thieving skills, then everything is fine (as far as the UI is concerned...). But if that's the case, then the only meaningful skill is SET_TRAPS. As you said, everything else requires special toolbar buttons which are not available by default for these classes.

**Comment by Argent77** [comment]
Solved in [v0.4.0](https://github.com/Argent77/A7-add_kit_ex/releases/tag/v0.4.0).
