### ISSUE TITLE
[Documentation] You should specify "hpclass" only for Single-class Kits

### ISSUE THREAD

**Issue by 4Luke4** [Argent77/A7-add_kit_ex#2]
Pretty much what the title states (provided it's not an engine bug!).

For instance, let's code a Fighter/Thief kit, set `"hpclass" = "HPBARB"` when launching `ADD_KIT_EX` and start a new BG:EE game.
As you can see, your character will have `8/8` hit points (as if it were using `HPFT.2DA`).

Moreover, things don't change if you edit the default table for `FIGHTER_THIEF` (i.e., `HPFT.2DA`) or edit `HPCLASS.2DA` so that `FIGHTER_THIEF` points to a different `2DA` table.

As a result, documentation should clearly state this hardcoded behavior both when introducing the parameter `hpclass` and when speaking about Multiclass Kits limitations.

**Comment by Argent77** [comment]
Yeah, multiclass kits are special in many ways. I'll update the readme accordingly.
