### ISSUE TITLE
multiclasses not always generating QD_MCx spells

### ISSUE THREAD

**Issue by subtledoctor** [Argent77/A7-add_kit_ex#5]
I made a fighter/thief and specified 
- class = 9
- base_class = ~T~
- clab_path = ~mymod/data/clab.2da~

...and it didn't work. No QDmulti files were generated, nothing added to CLABTH01.2da, so the kit didn't get any abilities. Then I tried the alternate method:
- class = 9
- clab_base_t = ~mymod/data/clab.2da~

...and that worked. 

I took from the instructions that those should be equal, but it seems like the base_class. variable being set is not triggering the QDmulti stuff to be created.

**Comment by Argent77** [comment]
I can confirm this issue. You're right, that both methods should produce comparable results. I'll look into it.

**Comment by Argent77** [comment]
Fixed (3d0b537d70585b89d31a402df89427dc2e0b9e33). It was caused by a typo in one of the variable names.

**Comment by SarahG-579462** [comment]
ha I should have checked for new releases, spent an hour or so debugging and found the same typo 😝
