### ISSUE TITLE
*.2da entry in kitlist.2da compatibility issues

### ISSUE THREAD

**Issue by TheArtisanBG** [Argent77/A7-add_kit_ex#9]
Someone at G3 discord raised a compatibility issue and I'm not certain if it's this tool, but I'm going to submit it anyway. From what I can tell since multi-class kits can't use clab files normally the tool just defaults to *.2da, which is normally fine but it seems a mod which reads the abilities header to mass append to clab files (in this case subtledoctor's mod) tries to read the *.2da as an actual file which doesn't actually exist. So I tried to add to the clab_path section for my multi-class kits but it looks like it won't add the entries even then if it detects it's a multi-class.

I don't know if it's actually the way the tool works or if it's even your responsibility to fix it, but I thought I'd raise the issue (?) just in case.

**Comment by Argent77** [comment]
I'm hesitant to add actual CLAB resrefs instead of the default placeholder for multiclass kits since they are ignored by the engine. I think that would rather encourage modders to use these CLABs in some way even though they are never actually used by the kits.
